# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Server CI/CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  S3_BUCKET_NAME: u-life-kurly--build
  CODE_DEPLOY_APPLICATION_NAME: u-life-kurly
  CODE_DEPLOY_APPLICATION_GROUP: u_life_kurly-deploy-group

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
        
    - name: Make File Zip
      run: zip -r ./u_life_kurly-build.zip .
    - name: Save at AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      run: aws s3 cp --region ap-northeast-2 --acl private ./u_life_kurly-build.zip s3://$S3_BUCKET_NAME/
      
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      run: >
        aws deploy create-deployment --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} 
        --deployment-group-name ${{ env.CODE_DEPLOY_APPLICATION_GROUP }} --region ap-northeast-2 
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=u_life_kurly-build.zip
      
      
